### ISSUE TITLE
Обновление до Home Assistant 2023.6.X

### ISSUE THREAD

**Issue by panfmik** [dmamontov/hass-tattelecom-intercom#5]
**Describe the bug**
После обновления интеграция перестала работать, повторный вход не происходит.

[custom_components.tattelecom_intercom.client] Successful request (https://domofon.tattelecom.ru/ApiVersion.V1/subscriber/signin): b'An internal server error occurred.'
[custom_components.tattelecom_intercom.client] Connection error (https://domofon.tattelecom.ru/ApiVersion.V1/subscriber/signin): Expecting value: line 1 column 1 (char 0)

![image](https://github.com/dmamontov/hass-tattelecom-intercom/assets/76124235/71d1565b-40bd-4cbd-a781-95ad37c2ad1e)

Откатился назад на версию Home Assistant 2023.5 все работает исправно

**Please complete the following information:**
 - HASS version: 2023.6.1
 - Component version v2.0.0

**Comment by JudeCrew** [comment]
Подтверждаю, такая же история. НА не откатывал, очень жду исправления :)

**Comment by SzenProgs** [comment]
Присоединяюсь. Такая же ошибка. Включил логирование в hass. В журналах логов нету.

**Comment by els777** [comment]
Автор забил? Сейчас обновился до версии 2023.9.3
Интеграция не работает.
Эта ошибка возникла в пользовательской интеграции.

```
Logger: aiohttp.server
Source: custom_components/tattelecom_intercom/updater.py:19
Integration: Таттелеком Домофон (documentation, issues)
First occurred: 08:22:08 (1 occurrences)
Last logged: 08:22:08

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 87, in delete
    result = await hass.config_entries.async_remove(entry_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1080, in async_remove
    await entry.async_remove(self.hass)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 578, in async_remove
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 818, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/tattelecom_intercom/__init__.py", line 30, in <module>
    from .updater import IntercomUpdater
  File "/config/custom_components/tattelecom_intercom/updater.py", line 19, in <module>
    from homeassistant.helpers.entity import DeviceEntryType, DeviceInfo
ImportError: cannot import name 'DeviceEntryType' from 'homeassistant.helpers.entity' (/usr/src/homeassistant/homeassistant/helpers/entity.py)
```
